#!/usr/bin/env bash
# Re-apply edits to the generated macos/ project.
#
# macos/ is gitignored and regenerated by `expo-desktop prebuild`, so anything
# changed inside it is a build artifact. Run this after every prebuild.
#
#   ./scripts/apply-native-patches.sh
#
# Long term these belong in an Expo config plugin, if expo-desktop turns out to
# run config plugins for macOS — see docs/PLATFORM.md section 6.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENTITLEMENTS="$ROOT/macos/DriveSweep-macOS/DriveSweep.entitlements"

if [[ ! -f "$ENTITLEMENTS" ]]; then
  echo "error: $ENTITLEMENTS not found — run prebuild first." >&2
  exit 1
fi

pb() { /usr/libexec/PlistBuddy -c "$1" "$ENTITLEMENTS" >/dev/null 2>&1; }

# DriveSweep cannot work sandboxed: it has to read ~/Library, /Library/Developer
# and /opt/homebrew, none of which a sandboxed app can enumerate. There is also
# no way to ask for them — expo-file-system's directory picker rejects on macOS.
# Unsandboxed + Full Disk Access is what every comparable tool ships.
# See docs/PLATFORM.md section 2.
pb "Set :com.apple.security.app-sandbox false" \
  || pb "Add :com.apple.security.app-sandbox bool false"

# Pointless once unsandboxed, and misleading to leave behind.
pb "Delete :com.apple.security.files.user-selected.read-only" || true

echo "Applied native patches:"
echo "  app-sandbox = $(/usr/libexec/PlistBuddy -c 'Print :com.apple.security.app-sandbox' "$ENTITLEMENTS" 2>/dev/null || echo '?')"
